[project]
name = 'Decentralized-Public-Mailbox-and-Postal-Infrastructure-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mail-forwarding-coordination]
path = 'contracts/mail-forwarding-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.mail-slot-installation]
path = 'contracts/mail-slot-installation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
